### ISSUE TITLE
Make layer count on map (heatmap) accurate

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#133]
Make layer count on map accurate.  This might mean additional query to Solr.  There is count used to create heatmap and actual count.  We want actual count to be used in tool tip on map, but heatmap count to be used to control heatmap display.

**Comment by capooti** [comment]
Any reason why this is not accurate? Is it a Solr thing, or our implementation?

**Comment by blewis** [comment]
we generate heatmaps which exclude background layers to heatmaps are not muddy and have good contrast.  one solution is to return two arrays one for display and the other for counts.  there was a discussion on Slack a while back on best way to handle this with Ariel and David, can't find it now

**Comment by dsmiley** [comment]
You could ask Solr for two heatmaps, one for display that filters out large maps/layers, and the second for tooltips -- possibly more detailed which doesn't filter the big layers.  They should probably be done in separate requests to Solr to speed the time to display, and because perhaps you can delay the fetch for the 2nd until the mouse is in the map (if that ever even happens).

**Comment by blewis** [comment]
Excellent idea!

**Comment by capooti** [comment]
Thanks for the idea @dsmiley
