### ISSUE TITLE
Gazetteer tool is not using Google as one of its gazetteers

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#245]

**Comment by capooti** [comment]
@bglewis we enbled geonames in place of google as the default gazetteer by choice:

https://github.com/cga-harvard/cga-worldmap/commit/3e7e6e96c32816eae589503c280201bfcbf672c2

One of the reason was that searching "cambridge" was returning just the city in UK.

The "Advanced" menu is working as expected, but there is a CSS issue which was introduced by the new "blank" theme, which was already reported here:

https://github.com/cga-harvard/cga-worldmap/issues/225

**Comment by blewis** [comment]
I understand Google is off by default but even when I turned it on it is not finding an address.  Is Google Places broken?  If so then we should remove it as a choice until we fix it.  We don't have to fix it now.

**Comment by capooti** [comment]
It may be tricky to enable the "Google" service using the CSS broken form, but Google get back results if active:

![screenshot 2017-06-14 10 56 09](https://user-images.githubusercontent.com/148380/27139138-33bf232e-50f0-11e7-8d8d-df0f995086f5.png)

**Comment by capooti** [comment]
This is the Google endpoint that WM is using behind the scenes:

https://maps.googleapis.com/maps/api/geocode/json?address=cambridge

Everything in the "search" text box will also return results from the google endpoint when the google gazeeteer is enabled

**Comment by capooti** [comment]
the service can be tested using this UI:

https://developers.google.com/maps/documentation/geocoding/intro#geocoding

**Comment by capooti** [comment]
The broken CSS is confusing. When the Google checkbox is correctly selected, then you will see results:

![screenshot 2017-06-14 12 06 07](https://user-images.githubusercontent.com/148380/27142721-f6dcf4a4-50f9-11e7-8f04-82f8800f60f4.png)
