### ISSUE TITLE
pavement.py can't find GeoNode context

### ISSUE THREAD

**Issue by lannio** [cga-harvard/geonode#275]
I installed the project normally according to the installation step (https://github.com/cga-harvard/geonode/tree/worldmap/geonode/contrib/worldmap), but I can't start geoserver.
![image](https://user-images.githubusercontent.com/33817803/36071510-41e61b9c-0f4a-11e8-8372-09e948c7c403.png)

**Comment by capooti** [comment]
@lannio I have seen this happening on a few instances. I believe it is because of a problem of Python paths.

As a workaround put an ipdb (or pdb) breakpoint just before the first try block in pavement.py:

import ipdb; ipdb.set_trace()
try:
     import ipdb; ipdb.set_trace()
    from worldmap.settings import GEONODE_APPS, OGC_SERVER, INSTALLED_APPS
...

I will see if there is a definite way to fix this with others GeoNode developers.
I am renaming the tickets to the appropriate problem.

**Comment by capooti** [comment]
@lannio this fixes the problem:
https://github.com/cga-harvard/geonode-project/commit/99fed785716c320730f85d146ea6978e951abbf0

If you don't want to start the project from scratch, just copy the content of this file to your pavement.py file, replacing {{ project_name }} with your project name.
Let me know if you need further assistance.
