### ISSUE TITLE
Line style appears 5X thicker in legend than on map

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#335]
In this example with two lines, one 1 pixel wide and one 3 pixels wide, one style appears as large dot on legend.  
![image](https://user-images.githubusercontent.com/812849/38523547-df009442-3c19-11e8-815c-2a803bd242e9.png)

**Comment by capooti** [comment]
This looks very strange. I can't replicate this in my local development environment. I would say to leave it out at this time, and maybe tackle it if we encounter it in production.

**Comment by capooti** [comment]
Oh, figured out: this looks to be a bug in GeoServer 2.12.2 http://osgeo-org.1560.x6.nabble.com/Issues-with-GetLegendGraphic-stroke-width-in-LineSymbolizer-since-2-12-2-td5353147.html
This has been fixed in current GeoServer build.
I am checking with GeoServer developers to have an updated GeoServer built for GeoNode.

**Comment by capooti** [comment]
This is now fixed. It was enough to upgrade to GeoServer 2.12.2.
